DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
  'Main',
  'Snack',
  'Lunch',
  'Breakfast'
);

DROP TABLE IF EXISTS shopping_list;
CREATE TABLE IF NOT EXISTS shopping_list (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  price decimal(12,2) NOT NULL,
  date_added TIMESTAMPTZ DEFAULT now() NOT NULL,
  checked BOOLEAN DEFAULT FALSE NOT NULL,
  category grocery NOT NULL
);



